use std::process::{Command, Stdio};
use std::io::{BufRead, BufReader};
use std::sync::RwLock;
use std::collections::HashSet;
use std::collections::HashMap;
use std::sync::Arc;
use std::fs::File;
use std::thread;
use std::time;

const TIMEOUT: u32 = 5000; // 5 sec
const TMC_DECAY_AGE: u32 = 10 * 60 * 1000; // 10 min

struct LookupMaps {
	slowdown: HashMap<u32, f64>,
	descs: HashMap<u32, &'static str>
}

pub fn init_tmc_threads(tmc_arc: Arc<RwLock<::data::TMCState>>, data_arc: Arc<::data::State>) {
	let lookup = build_maps();

	//insert_dummy_events(tmc_arc, data_arc, lookup);
	//run_rdsd_loop(tmc_arc, data_arc);

	let tmc_arc_listener = tmc_arc.clone();
	let tmc_arc_timeout = tmc_arc.clone();

	let _ = thread::Builder::new().name("tmc_listener_thread".to_string()).spawn(move || {
		run_rdsd_loop(tmc_arc_listener.clone(), data_arc.clone(), &lookup);
	});
	let _ = thread::Builder::new().name("tmc_timeout_thread".to_string()).spawn(move || {
		run_timeout_loop(tmc_arc_timeout.clone());
	});
}

fn run_timeout_loop(tmc_arc: Arc<RwLock<::data::TMCState>>) {
	println!("[TIMEOUT] thread started");
	loop {
		{
			let mut state = tmc_arc.write().unwrap();

			// update timeout
			for (_, entry) in state.current_tmc_events.iter_mut() {
				entry.timeout += TIMEOUT;
			}

			let update_cnt = state.current_tmc_events.len();

			// collect decayed (key,val)
			let decayed: Vec<_> = state.current_tmc_events.iter().filter(|&(_, v)| v.timeout >= TMC_DECAY_AGE).map(|(k, _)| k.clone()).collect();

			for key in &decayed {
				if let Some(value) = state.current_tmc_events.remove(key) {
					for edge in value.edges {
						state.current_edge_events.remove(&edge);
					}
				}
			}
			println!("[TIMEOUT] updated {} entries, removed {} decayed entries, new cnt: {}", update_cnt, decayed.len(), state.current_tmc_events.len());
		}

		let timeout = time::Duration::from_millis(TIMEOUT as u64);
		thread::sleep(timeout);
	}
}

fn insert_dummy_events(tmc_arc: Arc<RwLock<::data::TMCState>>, data: Arc<::data::State>, lookup: &LookupMaps) {
	let f = File::open("rds/sample_events.log").unwrap();
	let f = BufReader::new(f);

	let mut state = tmc_arc.write().unwrap();

	for line in f.lines() {
		if let Some(event) = parse_tmc_event(line.unwrap()) {
			handle_event(event, &mut state, &data, &lookup);
		}
	}

	println!("tmc_events: {}", state.current_tmc_events.len());
	println!("edge_events: {}", state.current_edge_events.len());
}

fn parse_tmc_event(line: String) -> Option<::data::TMCRawEvent> {
	let mut vars = line.split_whitespace();

	let mut raw_event = ::data::TMCRawEvent { loc: 0, dir: true, event: 0, ext: 0 };

	if let Some(tmc_type) = vars.nth(0) {
		if tmc_type == "GF" || tmc_type == "S" {
			for pair in vars {
				let mut split_pair = pair.split("=");

				let key_raw = split_pair.nth(0);
				let value_raw = split_pair.last();

				if let (Some(key), Some(value)) = (key_raw, value_raw) {
					if let Ok(value_num) = value.parse::<u32>() {
						match key {
							"loc" => raw_event.loc = value_num,
							"ext" => raw_event.ext = value_num,
							"dir" => raw_event.dir = value_num == 1,
							"evt" => raw_event.event = value_num,
							_ => {},
						};
					}
				}
			}
		}
	}

	if raw_event.loc != 0 && raw_event.event != 0 {
		return Some(raw_event);
	} else {
		return None;
	}
}

fn handle_event(raw_event: ::data::TMCRawEvent, state: &mut ::data::TMCState, data: &::data::State, lookup: &LookupMaps) {
	let tmc_ids = build_tmc_range_set(&raw_event, data);

	let slowdown = lookup_slowdown(&raw_event.event, &lookup.slowdown);
	let desc = lookup_desc(&raw_event.event, &lookup.descs);

	let key = ::data::TMCKey { dir: raw_event.dir, loc: raw_event.loc, event: raw_event.event };
	let mut value = ::data::TMCEvent { ext: raw_event.event, desc: desc, edges: HashSet::new(), slowdown: slowdown, timeout: 1000 * 10 };

	for tmc_id in tmc_ids {
		if let Some(edges) = data.routing_data.tmc_mapping.get(&tmc_id) {
			for edge in edges {
				value.edges.insert(*edge);
				state.current_edge_events.insert(*edge, slowdown);
			}
		}
	}

	if !value.edges.is_empty() {
		state.current_tmc_events.insert(key, value);
	} else {
		println!("no edges found for loc id {}", raw_event.loc);
	}
}

fn build_maps() -> LookupMaps {
	let event_desc_map = build_event_desc_map();
	let event_slowdown_map = build_event_slowdown_map(&event_desc_map);

	return LookupMaps { descs: event_desc_map, slowdown: event_slowdown_map };
}

fn lookup_slowdown(event: &u32, map: &HashMap<u32, f64>) -> f64 {
	return *map.get(event).unwrap_or(&1f64);
}

fn lookup_desc(event: &u32, map: &HashMap<u32, &str>) -> String {
	return map.get(event).map(|desc| desc.to_string()).unwrap_or(format!("No description found for event id {}", event));
}

fn build_tmc_range_set(raw_event: &::data::TMCRawEvent, data: &::data::State) -> Vec<u32> {
	let mut result = Vec::new();
	result.push(raw_event.loc);

	if raw_event.ext == 0 {
		return result;
	}

	let mut curr_id = raw_event.loc;
	let mut curr_dist = raw_event.ext;

	while let Some(next_id) = data.routing_data.tmc_next.get(&(curr_id, raw_event.dir)) {
		result.push(*next_id);

		curr_id = *next_id;
		curr_dist -= 1;

		if curr_dist == 0 {
			break;
		}
	}

	println!("range_set for loc {} {} {} = {:?}", raw_event.loc, raw_event.dir, raw_event.ext, result);

	return result;
}

fn run_rdsd_loop(tmc_arc: Arc<RwLock<::data::TMCState>>, data_arc: Arc<::data::State>, lookup: &LookupMaps) {
	println!("[RDSD] thread started");

	let rdsd_child_raw = Command::new("rdsd").stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).spawn();
	let rdsquery_child_raw = Command::new("rdsquery").arg("-s").arg("localhost").arg("-c").arg("0").arg("-t").arg("tmc").stdin(Stdio::null()).stdout(Stdio::piped()).stderr(Stdio::null()).spawn();

	if let (Ok(mut rdsd_child), Ok(mut rdsquery_child)) = (rdsd_child_raw, rdsquery_child_raw) {
		println!("[RDSD] successfully spawned rdsd ({}) and rdsquery ({})", rdsd_child.id(), rdsquery_child.id());

		let buf_reader = BufReader::new(rdsquery_child.stdout.as_mut().unwrap());

		for line in buf_reader.lines() {
			if let Ok(content) = line {
				if let Some(event) = parse_tmc_event(content) {
					let mut state = tmc_arc.write().unwrap();
					handle_event(event, &mut state, &data_arc, &lookup);
				}
			}
		}

		let _ = rdsd_child.kill();
	} else {
		println!("[RDSD] failed to start rdsd and rdsquery, will load sample events");
		insert_dummy_events(tmc_arc, data_arc, &lookup);
	}

	println!("[RDSD] thread ended");
}

fn build_event_slowdown_map(map_desc: &HashMap<u32, &str>) -> HashMap<u32, f64> {
	let mut r = HashMap::new();

	let mut cnt_unmapped = 0;

	for (event, desc_raw) in map_desc {
		let desc = desc_raw.to_string().to_lowercase();

		if desc.contains("bridge closed") || desc.contains("tunnel closed") || desc.contains("bridge blocked") || desc.contains("tunnel blocked") {
			r.insert(*event, 0.99);
		} else if desc.contains("stationary traffic") {
			r.insert(*event, 0.95);
		} else if desc.contains("queuing traffic") {
			r.insert(*event, 0.80);
		} else if desc.contains("slow traffic") {
			r.insert(*event, 0.50);
		} else if desc.contains("heavy traffic") {
			r.insert(*event, 0.30);
		} else if desc.contains("construction work") || desc.contains("roadworks") || desc.contains("resurfacing work") || desc.contains("road marking work") {
			r.insert(*event, 0.60);
		} else if desc.contains("traffic problem") {
			r.insert(*event, 0.15);
		} else if desc.contains("accident") {
			r.insert(*event, 0.75);
		} else {
			//println!("no slowdown entry for event code {} with desc: {}", event, desc_raw);
			cnt_unmapped += 1;
		}
	}
	println!("no slowdown entry for {} of {} event codes ({}%)", cnt_unmapped, map_desc.len(), (cnt_unmapped as f32 / map_desc.len() as f32) * 100.0);
	return r;
}

fn build_event_desc_map() -> HashMap<u32, &'static str> {
	let mut r = HashMap::new();

	r.insert(1, "traffic problem");
	r.insert(2, "queuing traffic (with average speeds Q). Danger of stationary traffic");
	r.insert(11, "overheight warning system triggered");
	r.insert(12, "(Q) accident(s), traffic being directed around accident area");
	r.insert(16, "closed, rescue and recovery work in progress");
	r.insert(20, "service area overcrowded, drive to another service area");
	r.insert(22, "service area, fuel station closed");
	r.insert(23, "service area, restaurant closed");
	r.insert(24, "bridge closed");
	r.insert(25, "tunnel closed");
	r.insert(26, "bridge blocked");
	r.insert(27, "tunnel blocked");
	r.insert(28, "road closed intermittently");
	r.insert(36, "fuel station reopened");
	r.insert(37, "restaurant reopened");
	r.insert(40, "smog alert ended");
	r.insert(41, "(Q) overtaking lane(s) closed");
	r.insert(42, "(Q) overtaking lane(s) blocked");
	r.insert(51, "roadworks, (Q) overtaking lane(s) closed");
	r.insert(52, "(Q sets of) roadworks on the hard shoulder");
	r.insert(53, "(Q sets of) roadworks in the emergency lane");
	r.insert(55, "traffic problem expected");
	r.insert(56, "traffic congestion expected");
	r.insert(57, "normal traffic expected");
	r.insert(61, "(Q) object(s) on roadway {something that does not neccessarily block the road or part of it}");
	r.insert(62, "(Q) burst pipe(s)");
	r.insert(63, "(Q) object(s) on the road. Danger");
	r.insert(64, "burst pipe. Danger");
	r.insert(70, "traffic congestion, average speed of  10 km/h");
	r.insert(71, "traffic congestion, average speed of  20 km/h");
	r.insert(72, "traffic congestion, average speed of  30 km/h");
	r.insert(73, "traffic congestion, average speed of  40 km/h");
	r.insert(74, "traffic congestion, average speed of  50 km/h");
	r.insert(75, "traffic congestion, average speed of  60 km/h");
	r.insert(76, "traffic congestion, average speed of  70 km/h");
	r.insert(91, "delays (Q) for cars");
	r.insert(101, "stationary traffic");
	r.insert(102, "stationary traffic for 1 km");
	r.insert(103, "stationary traffic for 2 km");
	r.insert(104, "stationary traffic for 4 km");
	r.insert(105, "stationary traffic for 6 km");
	r.insert(106, "stationary traffic for 10 km");
	r.insert(107, "stationary traffic expected");
	r.insert(108, "queuing traffic (with average speeds Q)");
	r.insert(109, "queuing traffic for 1 km (with average speeds Q)");
	r.insert(110, "queuing traffic for 2 km (with average speeds Q)");
	r.insert(111, "queuing traffic for 4 km (with average speeds Q)");
	r.insert(112, "queuing traffic for 6 km (with average speeds Q)");
	r.insert(113, "queuing traffic for 10 km (with average speeds Q)");
	r.insert(114, "queuing traffic expected");
	r.insert(115, "slow traffic (with average speeds Q)");
	r.insert(116, "slow traffic for 1 km (with average speeds Q)");
	r.insert(117, "slow traffic for 2 km (with average speeds Q)");
	r.insert(118, "slow traffic for 4 km (with average speeds Q)");
	r.insert(119, "slow traffic for 6 km (with average speeds Q)");
	r.insert(120, "slow traffic for 10 km (with average speeds Q)");
	r.insert(121, "slow traffic expected");
	r.insert(122, "heavy traffic (with average speeds Q)");
	r.insert(123, "heavy traffic expected");
	r.insert(124, "traffic flowing freely (with average speeds Q)");
	r.insert(125, "traffic building up (with average speeds Q) ");
	r.insert(126, "no problems to report");
	r.insert(127, "traffic congestion cleared");
	r.insert(128, "message cancelled");
	r.insert(129, "stationary traffic for 3 km");
	r.insert(130, "danger of stationary traffic");
	r.insert(131, "queuing traffic for 3 km (with average speeds Q)");
	r.insert(132, "danger of queuing traffic (with average speeds Q)");
	r.insert(133, "long queues (with average speeds Q)");
	r.insert(134, "slow traffic for 3 km (with average speeds Q)");
	r.insert(135, "traffic easing");
	r.insert(136, "traffic congestion (with average speeds Q)");
	r.insert(137, "traffic lighter than normal (with average speeds Q)");
	r.insert(138, "queuing traffic (with average speeds Q). Approach with care");
	r.insert(139, "queuing traffic around a bend in the road");
	r.insert(140, "queuing traffic over the crest of a hill");
	r.insert(141, "all accidents cleared, no problems to report");
	r.insert(142, "traffic heavier than normal (with average speeds Q)");
	r.insert(143, "traffic very much heavier than normal (with average speeds Q)");
	r.insert(200, "multi vehicle pile up. Delays (Q)");
	r.insert(201, "(Q) accident(s)");
	r.insert(202, "(Q) serious accident(s)");
	r.insert(203, "multi-vehicle accident (involving Q vehicles)");
	r.insert(204, "accident involving (a/Q) heavy lorr(y/ies)");
	r.insert(205, "(Q) accident(s) involving hazardous materials");
	r.insert(206, "(Q) fuel spillage accident(s)");
	r.insert(207, "(Q) chemical spillage accident(s)");
	r.insert(208, "vehicles slowing to look at (Q) accident(s)");
	r.insert(209, "(Q) accident(s) in the opposing lanes");
	r.insert(210, "(Q) shed load(s)");
	r.insert(211, "(Q) broken down vehicle(s)");
	r.insert(212, "(Q) broken down heavy lorr(y/ies) ");
	r.insert(213, "(Q) vehicle fire(s)");
	r.insert(214, "(Q) incident(s)");
	r.insert(215, "(Q) accident(s). Stationary traffic");
	r.insert(216, "(Q) accident(s). Stationary traffic for 1 km ");
	r.insert(217, "(Q) accident(s). Stationary traffic for 2 km");
	r.insert(218, "(Q) accident(s). Stationary traffic for 4 km");
	r.insert(219, "(Q) accident(s). Stationary traffic for 6 km");
	r.insert(220, "(Q) accident(s). Stationary traffic for 10 km");
	r.insert(221, "(Q) accident(s). Danger of stationary traffic ");
	r.insert(222, "(Q) accident(s). Queuing traffic ");
	r.insert(223, "(Q) accident(s). Queuing traffic for 1 km");
	r.insert(224, "(Q) accident(s). Queuing traffic for 2 km");
	r.insert(225, "(Q) accident(s). Queuing traffic for 4 km");
	r.insert(226, "(Q) accident(s). Queuing traffic for 6 km");
	r.insert(227, "(Q) accident(s). Queuing traffic for 10 km");
	r.insert(228, "(Q) accident(s). Danger of queuing traffic");
	r.insert(229, "(Q) accident(s). Slow traffic ");
	r.insert(230, "(Q) accident(s). Slow traffic for 1 km");
	r.insert(231, "(Q) accident(s). Slow traffic for 2 km");
	r.insert(232, "(Q) accident(s). Slow traffic for 4 km ");
	r.insert(233, "(Q) accident(s). Slow traffic for 6 km");
	r.insert(234, "(Q) accident(s). Slow traffic for 10 km");
	r.insert(235, "(Q) accident(s). Slow traffic expected");
	r.insert(236, "(Q) accident(s). Heavy traffic ");
	r.insert(237, "(Q) accident(s). Heavy traffic expected");
	r.insert(238, "(Q) accident(s). Traffic flowing freely");
	r.insert(239, "(Q) accident(s). Traffic building up");
	r.insert(240, "road closed due to (Q) accident(s)");
	r.insert(241, "(Q) accident(s). Right lane blocked");
	r.insert(242, "(Q) accident(s). Centre lane blocked");
	r.insert(243, "(Q) accident(s). Left lane blocked");
	r.insert(244, "(Q) accident(s). Hard shoulder blocked");
	r.insert(245, "(Q) accident(s). Two lanes blocked");
	r.insert(246, "(Q) accident(s). Three lanes blocked");
	r.insert(247, "accident. Delays (Q)");
	r.insert(248, "accident. Delays (Q) expected");
	r.insert(249, "accident. Long delays (Q)");
	r.insert(250, "vehicles slowing to look at (Q) accident(s). Stationary traffic");
	r.insert(251, "vehicles slowing to look at (Q) accident(s). Stationary traffic for 1 km");
	r.insert(252, "vehicles slowing to look at (Q) accident(s). Stationary traffic for 2 km");
	r.insert(253, "vehicles slowing to look at (Q) accident(s). Stationary traffic for 4 km");
	r.insert(254, "vehicles slowing to look at (Q) accident(s). Stationary traffic for 6 km");
	r.insert(255, "vehicles slowing to look at (Q) accident(s). Stationary traffic for 10 km");
	r.insert(256, "vehicles slowing to look at (Q) accident(s). Danger of stationary traffic");
	r.insert(257, "vehicles slowing to look at (Q) accident(s). Queuing traffic ");
	r.insert(258, "vehicles slowing to look at (Q) accident(s). Queuing traffic for 1 km");
	r.insert(259, "vehicles slowing to look at (Q) accident(s). Queuing traffic for 2 km");
	r.insert(260, "vehicles slowing to look at (Q) accident(s). Queuing traffic for 4 km");
	r.insert(261, "vehicles slowing to look at (Q) accident(s). Queuing traffic for 6 km");
	r.insert(262, "vehicles slowing to look at (Q) accident(s). Queuing traffic for 10 km");
	r.insert(263, "vehicles slowing to look at (Q) accident(s). Danger of queuing traffic");
	r.insert(264, "vehicles slowing to look at (Q) accident(s). Slow traffic");
	r.insert(265, "vehicles slowing to look at (Q) accident(s). Slow traffic for 1 km");
	r.insert(266, "vehicles slowing to look at (Q) accident(s). Slow traffic for 2 km");
	r.insert(267, "vehicles slowing to look at (Q) accident(s). Slow traffic for 4 km");
	r.insert(268, "vehicles slowing to look at (Q) accident(s). Slow traffic for 6 km");
	r.insert(269, "vehicles slowing to look at (Q) accident(s). Slow traffic for 10 km");
	r.insert(270, "vehicles slowing to look at (Q) accident(s). Slow traffic expected");
	r.insert(271, "vehicles slowing to look at (Q) accident(s). Heavy traffic");
	r.insert(272, "vehicles slowing to look at (Q) accident(s). Heavy traffic expected");
	r.insert(274, "vehicles slowing to look at (Q) accident(s). Traffic building up");
	r.insert(275, "vehicles slowing to look at accident. Delays (Q)");
	r.insert(276, "vehicles slowing to look at accident. Delays (Q) expected");
	r.insert(277, "vehicles slowing to look at accident. Long delays (Q)");
	r.insert(278, "(Q) shed load(s). Stationary traffic");
	r.insert(279, "(Q) shed load(s). Stationary traffic for 1 km");
	r.insert(280, "(Q) shed load(s). Stationary traffic for 2 km");
	r.insert(281, "(Q) shed load(s). Stationary traffic for 4 km");
	r.insert(282, "(Q) shed load(s). Stationary traffic for 6 km");
	r.insert(283, "(Q) shed load(s). Stationary traffic for 10 km");
	r.insert(284, "(Q) shed load(s). Danger of stationary traffic ");
	r.insert(285, "(Q) shed load(s). Queuing traffic ");
	r.insert(286, "(Q) shed load(s). Queuing traffic for 1 km");
	r.insert(287, "(Q) shed load(s). Queuing traffic for 2 km");
	r.insert(288, "(Q) shed load(s). Queuing traffic for 4 km");
	r.insert(289, "(Q) shed load(s). Queuing traffic for 6 km");
	r.insert(290, "(Q) shed load(s). Queuing traffic for 10 km");
	r.insert(291, "(Q) shed load(s). Danger of queuing traffic");
	r.insert(292, "(Q) shed load(s). Slow traffic ");
	r.insert(293, "(Q) shed load(s). Slow traffic for 1 km");
	r.insert(294, "(Q) shed load(s). Slow traffic for 2 km");
	r.insert(295, "(Q) shed load(s). Slow traffic for 4 km");
	r.insert(296, "(Q) shed load(s). Slow traffic for 6 km");
	r.insert(297, "(Q) shed load(s). Slow traffic for 10 km");
	r.insert(298, "(Q) shed load(s). Slow traffic expected");
	r.insert(299, "(Q) shed load(s). Heavy traffic");
	r.insert(300, "(Q) shed load(s). Heavy traffic expected");
	r.insert(301, "(Q) shed load(s). Traffic flowing freely");
	r.insert(302, "(Q) shed load(s). Traffic building up");
	r.insert(303, "blocked by (Q) shed load(s)");
	r.insert(304, "(Q) shed load(s). Right lane blocked ");
	r.insert(305, "(Q) shed load(s). Centre lane blocked");
	r.insert(306, "(Q) shed load(s). Left lane blocked");
	r.insert(307, "(Q) shed load(s). Hard shoulder blocked");
	r.insert(308, "(Q) shed load(s). Two lanes blocked ");
	r.insert(309, "(Q) shed load(s). Three lanes blocked");
	r.insert(310, "shed load. Delays (Q)");
	r.insert(311, "shed load. Delays (Q) expected");
	r.insert(312, "shed load. Long delays (Q)");
	r.insert(313, "(Q) broken down vehicle(s). Stationary traffic");
	r.insert(314, "(Q) broken down vehicle(s). Danger of stationary traffic");
	r.insert(315, "(Q) broken down vehicle(s). Queuing traffic");
	r.insert(316, "(Q) broken down vehicle(s). Danger of queuing traffic");
	r.insert(317, "(Q) broken down vehicle(s). Slow traffic ");
	r.insert(318, "(Q) broken down vehicle(s). Slow traffic expected");
	r.insert(319, "(Q) broken down vehicle(s). Heavy traffic");
	r.insert(320, "(Q) broken down vehicle(s). Heavy traffic expected");
	r.insert(321, "(Q) broken down vehicle(s). Traffic flowing freely");
	r.insert(322, "(Q) broken down vehicle(s).Traffic building up");
	r.insert(323, "blocked by (Q) broken down vehicle(s).");
	r.insert(324, "(Q) broken down vehicle(s). Right lane blocked ");
	r.insert(325, "(Q) broken down vehicle(s). Centre lane blocked");
	r.insert(326, "(Q) broken down vehicle(s). Left lane blocked ");
	r.insert(327, "(Q) broken down vehicle(s). Hard shoulder blocked ");
	r.insert(328, "(Q) broken down vehicle(s). Two lanes blocked ");
	r.insert(329, "(Q) broken down vehicle(s). Three lanes blocked");
	r.insert(330, "broken down vehicle. Delays (Q)");
	r.insert(331, "broken down vehicle. Delays (Q) expected");
	r.insert(332, "broken down vehicle. Long delays (Q)");
	r.insert(333, "accident cleared");
	r.insert(334, "message cancelled");
	r.insert(335, "accident involving (a/Q) bus(es)");
	r.insert(336, "(Q) oil spillage accident(s)");
	r.insert(337, "(Q) overturned vehicle(s)");
	r.insert(338, "(Q) overturned heavy lorr(y/ies)");
	r.insert(339, "(Q) jackknifed trailer(s)");
	r.insert(340, "(Q) jackknifed caravan(s)");
	r.insert(341, "(Q) jackknifed articulated lorr(y/ies)");
	r.insert(342, "(Q) vehicle(s) spun around");
	r.insert(343, "(Q) earlier accident(s)");
	r.insert(344, "accident investigation work");
	r.insert(345, "(Q) secondary accident(s)");
	r.insert(346, "(Q) broken down bus(es)");
	r.insert(347, "(Q) overheight vehicle(s)");
	r.insert(348, "(Q) accident(s). Stationary traffic for 3 km");
	r.insert(349, "(Q) accident(s). Queuing traffic for 3 km");
	r.insert(350, "(Q) accident(s). Slow traffic for 3 km");
	r.insert(351, "(Q) accident(s) in roadworks area");
	r.insert(352, "vehicles slowing to look at (Q) accident(s). Stationary traffic for 3 km");
	r.insert(353, "vehicles slowing to look at (Q) accident(s). Queuing traffic for 3 km");
	r.insert(354, "vehicles slowing to look at (Q) accident(s). Slow traffic for 3 km");
	r.insert(355, "vehicles slowing to look at (Q) accident(s). Danger");
	r.insert(356, "(Q) shed load(s). Stationary traffic for 3 km");
	r.insert(357, "(Q) shed load(s). Queuing traffic for 3 km");
	r.insert(358, "(Q) shed load(s). Slow traffic for 3 km");
	r.insert(359, "(Q) shed load(s). Danger");
	r.insert(360, "(Q) overturned vehicle(s). Stationary traffic");
	r.insert(361, "(Q) overturned vehicle(s). Danger of stationary traffic");
	r.insert(362, "(Q) overturned vehicle(s). Queuing traffic");
	r.insert(363, "(Q) overturned vehicle(s). Danger of queuing traffic ");
	r.insert(364, "(Q) overturned vehicle(s). Slow traffic ");
	r.insert(365, "(Q) overturned vehicle(s). Slow traffic expected");
	r.insert(366, "(Q) overturned vehicle(s). Heavy traffic");
	r.insert(367, "(Q) overturned vehicle(s). Heavy traffic expected");
	r.insert(368, "(Q) overturned vehicle(s). Traffic building up");
	r.insert(369, "blocked by (Q) overturned vehicle(s)");
	r.insert(370, "(Q) overturned vehicle(s). Right lane blocked ");
	r.insert(371, "(Q) overturned vehicle(s). Centre lane blocked");
	r.insert(372, "(Q) overturned vehicle(s). Left lane blocked ");
	r.insert(373, "(Q) overturned vehicle(s). Two lanes blocked ");
	r.insert(374, "(Q) overturned vehicle(s). Three lanes blocked");
	r.insert(375, "overturned vehicle. Delays (Q)");
	r.insert(376, "overturned vehicle. Delays (Q) expected");
	r.insert(377, "overturned vehicle. Long delays (Q)");
	r.insert(378, "(Q) overturned vehicle(s). Danger");
	r.insert(379, "Stationary traffic due to (Q) earlier accident(s)");
	r.insert(380, "Danger of stationary traffic due to (Q) earlier accident(s)");
	r.insert(381, "Queuing traffic due to (Q) earlier accident(s)");
	r.insert(382, "Danger of queuing traffic due to (Q) earlier accident(s) ");
	r.insert(383, "Slow traffic due to (Q) earlier accident(s) ");
	r.insert(385, "Heavy traffic due to (Q) earlier accident(s)");
	r.insert(387, "Traffic building up due to (Q) earlier accident(s)");
	r.insert(388, "Delays (Q) due to earlier accident");
	r.insert(390, "Long delays (Q) due to earlier accident");
	r.insert(391, "accident investigation work. Danger");
	r.insert(392, "(Q) secondary accident(s). Danger");
	r.insert(393, "(Q) broken down vehicle(s). Danger");
	r.insert(394, "(Q) broken down heavy lorr(y/ies). Danger");
	r.insert(395, "road cleared");
	r.insert(396, "incident cleared");
	r.insert(397, "rescue and recovery work in progress");
	r.insert(399, "message cancelled");
	r.insert(401, "closed");
	r.insert(402, "blocked");
	r.insert(403, "closed for heavy vehicles (over Q)");
	r.insert(404, "no through traffic for heavy lorries (over Q)");
	r.insert(405, "no through traffic ");
	r.insert(406, "(Q th) entry slip road closed");
	r.insert(407, "(Q th) exit slip road closed");
	r.insert(408, "slip roads closed");
	r.insert(409, "slip road restrictions");
	r.insert(410, "closed ahead. Stationary traffic ");
	r.insert(411, "closed ahead. Stationary traffic for 1 km");
	r.insert(412, "closed ahead. Stationary traffic for 2 km");
	r.insert(413, "closed ahead. Stationary traffic for 4 km");
	r.insert(414, "closed ahead. Stationary traffic for 6 km");
	r.insert(415, "closed ahead. Stationary traffic for 10 km");
	r.insert(416, "closed ahead. Danger of stationary traffic");
	r.insert(417, "closed ahead. Queuing traffic ");
	r.insert(418, "closed ahead. Queuing traffic for 1 km");
	r.insert(419, "closed ahead. Queuing traffic for 2 km");
	r.insert(420, "closed ahead. Queuing traffic for 4 km");
	r.insert(421, "closed ahead. Queuing traffic for 6 km");
	r.insert(422, "closed ahead. Queuing traffic for 10 km");
	r.insert(423, "closed ahead. Danger of queuing traffic");
	r.insert(424, "closed ahead. Slow traffic ");
	r.insert(425, "closed ahead. Slow traffic for 1 km");
	r.insert(426, "closed ahead. Slow traffic for 2 km");
	r.insert(427, "closed ahead. Slow traffic for 4 km");
	r.insert(428, "closed ahead. Slow traffic for 6 km");
	r.insert(429, "closed ahead. Slow traffic for 10 km");
	r.insert(430, "closed ahead. Slow traffic expected");
	r.insert(431, "closed ahead. Heavy traffic");
	r.insert(432, "closed ahead. Heavy traffic expected");
	r.insert(433, "closed ahead. Traffic flowing freely ");
	r.insert(434, "closed ahead. Traffic building up");
	r.insert(435, "closed ahead. Delays (Q)");
	r.insert(436, "closed ahead. Delays (Q) expected");
	r.insert(437, "closed ahead. Long delays (Q)");
	r.insert(438, "blocked ahead. Stationary traffic");
	r.insert(439, "blocked ahead. Stationary traffic for 1 km");
	r.insert(440, "blocked ahead. Stationary traffic for 2 km");
	r.insert(441, "blocked ahead. Stationary traffic for 4 km");
	r.insert(442, "blocked ahead. Stationary traffic for 6 km");
	r.insert(443, "blocked ahead. Stationary traffic for 10 km");
	r.insert(444, "blocked ahead. Danger of stationary traffic");
	r.insert(445, "blocked ahead. Queuing traffic ");
	r.insert(446, "blocked ahead. Queuing traffic for 1 km");
	r.insert(447, "blocked ahead. Queuing traffic for 2 km");
	r.insert(448, "blocked ahead. Queuing traffic for 4 km");
	r.insert(449, "blocked ahead. Queuing traffic for 6 km");
	r.insert(450, "blocked ahead. Queuing traffic for 10 km");
	r.insert(451, "blocked ahead. Danger of queuing traffic");
	r.insert(452, "blocked ahead. Slow traffic ");
	r.insert(453, "blocked ahead. Slow traffic for 1 km");
	r.insert(454, "blocked ahead. Slow traffic for 2 km");
	r.insert(455, "blocked ahead. Slow traffic for 4 km");
	r.insert(456, "blocked ahead. Slow traffic for 6 km");
	r.insert(457, "blocked ahead. Slow traffic for 10 km");
	r.insert(458, "blocked ahead. Slow traffic expected ");
	r.insert(459, "blocked ahead. Heavy traffic ");
	r.insert(460, "blocked ahead. Heavy traffic expected ");
	r.insert(461, "blocked ahead. Traffic flowing freely");
	r.insert(462, "blocked ahead. Traffic building up ");
	r.insert(463, "blocked ahead. Delays (Q)");
	r.insert(464, "blocked ahead. Delays (Q) expected");
	r.insert(465, "blocked ahead. Long delays (Q)");
	r.insert(466, "slip roads reopened");
	r.insert(467, "reopened");
	r.insert(468, "message cancelled");
	r.insert(469, "closed ahead");
	r.insert(470, "blocked ahead");
	r.insert(471, "(Q) entry slip road(s) closed");
	r.insert(472, "(Q th) entry slip road blocked");
	r.insert(473, "entry blocked");
	r.insert(474, "(Q) exit slip road(s) closed");
	r.insert(475, "(Q th) exit slip road blocked");
	r.insert(476, "exit blocked");
	r.insert(477, "slip roads blocked");
	r.insert(478, "connecting carriageway closed");
	r.insert(479, "parallel carriageway closed");
	r.insert(480, "right-hand parallel carriageway closed");
	r.insert(481, "left-hand parallel carriageway closed");
	r.insert(482, "express lanes closed");
	r.insert(483, "through traffic lanes closed");
	r.insert(484, "local lanes closed");
	r.insert(485, "connecting carriageway blocked");
	r.insert(486, "parallel carriageway blocked");
	r.insert(487, "right-hand parallel carriageway blocked");
	r.insert(488, "left-hand parallel carriageway blocked");
	r.insert(489, "express lanes blocked");
	r.insert(490, "through traffic lanes blocked");
	r.insert(491, "local lanes blocked");
	r.insert(492, "no motor vehicles");
	r.insert(493, "restrictions");
	r.insert(494, "closed for heavy lorries (over Q)");
	r.insert(495, "closed ahead. Stationary traffic for 3 km");
	r.insert(496, "closed ahead. Queuing traffic for 3 km");
	r.insert(497, "closed ahead. Slow traffic for 3 km");
	r.insert(498, "blocked ahead. Stationary traffic for 3 km");
	r.insert(499, "blocked ahead. Queuing traffic for 3 km");
	r.insert(500, "(Q) lane(s) closed");
	r.insert(501, "(Q) right lane(s) closed");
	r.insert(502, "(Q) centre lane(s) closed");
	r.insert(503, "(Q) left lane(s) closed");
	r.insert(504, "hard shoulder closed");
	r.insert(505, "two lanes closed");
	r.insert(506, "three lanes closed");
	r.insert(507, "(Q) right lane(s) blocked");
	r.insert(508, "(Q) centre lane(s) blocked");
	r.insert(509, "(Q) left lane(s) blocked");
	r.insert(510, "hard shoulder blocked");
	r.insert(511, "two lanes blocked");
	r.insert(512, "three lanes blocked");
	r.insert(513, "single alternate line traffic");
	r.insert(514, "carriageway reduced (from Q lanes) to one lane");
	r.insert(515, "carriageway reduced (from Q lanes) to two lanes ");
	r.insert(516, "carriageway reduced (from Q lanes) to three lanes");
	r.insert(517, "contraflow ");
	r.insert(518, "narrow lanes ");
	r.insert(519, "contraflow with narrow lanes ");
	r.insert(520, "(Q) lane(s) blocked");
	r.insert(521, "(Q) lanes closed. Stationary traffic ");
	r.insert(522, "(Q) lanes closed. Stationary traffic for 1 km");
	r.insert(523, "(Q) lanes closed. Stationary traffic for 2 km");
	r.insert(524, "(Q) lanes closed. Stationary traffic for 4 km");
	r.insert(525, "(Q) lanes closed. Stationary traffic for 6 km");
	r.insert(526, "(Q) lanes closed. Stationary traffic for 10 km");
	r.insert(527, "(Q) lanes closed. Danger of stationary traffic");
	r.insert(528, "(Q) lanes closed. Queuing traffic ");
	r.insert(529, "(Q) lanes closed. Queuing traffic for 1 km");
	r.insert(530, "(Q) lanes closed. Queuing traffic for 2 km");
	r.insert(531, "(Q) lanes closed. Queuing traffic for 4 km");
	r.insert(532, "(Q) lanes closed. Queuing traffic for 6 km");
	r.insert(533, "(Q) lanes closed. Queuing traffic for 10 km");
	r.insert(534, "(Q) lanes closed. Danger of queuing traffic");
	r.insert(535, "(Q) lanes closed. Slow traffic ");
	r.insert(536, "(Q) lanes closed. Slow traffic for 1 km");
	r.insert(537, "(Q) lanes closed. Slow traffic for 2 km");
	r.insert(538, "(Q) lanes closed. Slow traffic for 4 km");
	r.insert(539, "(Q) lanes closed. Slow traffic for 6 km");
	r.insert(540, "(Q) lanes closed. Slow traffic for 10 km");
	r.insert(541, "(Q) lanes closed. Slow traffic expected");
	r.insert(542, "(Q) lanes closed. Heavy traffic ");
	r.insert(543, "(Q) lanes closed. Heavy traffic expected ");
	r.insert(544, "(Q)lanes closed. Traffic flowing freely");
	r.insert(545, "(Q)lanes closed. Traffic building up ");
	r.insert(546, "carriageway reduced (from Q lanes) to one lane. Stationary traffic");
	r.insert(547, "carriageway reduced (from Q lanes) to one lane. Danger of stationary traffic");
	r.insert(548, "carriageway reduced (from Q lanes) to one lane. Queuing traffic");
	r.insert(549, "carriageway reduced (from Q lanes) to one lane. Danger of queuing traffic");
	r.insert(550, "carriageway reduced (from Q lanes) to one lane. Slow traffic");
	r.insert(551, "carriageway reduced (from Q lanes) to one lane. Slow traffic expected");
	r.insert(552, "carriageway reduced (from Q lanes) to one lane. Heavy traffic");
	r.insert(553, "carriageway reduced (from Q lanes) to one lane. Heavy traffic expected");
	r.insert(554, "carriageway reduced (from Q lanes) to one lane. Traffic flowing freely");
	r.insert(555, "carriageway reduced (from Q lanes) to one lane. Traffic building up");
	r.insert(556, "carriageway reduced (from Q lanes) to two lanes. Stationary traffic");
	r.insert(557, "carriageway reduced (from Q lanes) to two lanes. Danger of stationary traffic");
	r.insert(558, "carriageway reduced (from Q lanes) to two lanes. Queuing traffic");
	r.insert(559, "carriageway reduced (from Q lanes) to two lanes. Danger of queuing traffic");
	r.insert(560, "carriageway reduced (from Q lanes) to two lanes. Slow traffic");
	r.insert(561, "carriageway reduced (from Q lanes) to two lanes. Slow traffic expected");
	r.insert(562, "carriageway reduced (from Q lanes) to two lanes. Heavy traffic");
	r.insert(563, "carriageway reduced (from Q lanes) to two lanes. Heavy traffic expected ");
	r.insert(564, "carriageway reduced (from Q lanes) to two lanes. Traffic flowing freely");
	r.insert(565, "carriageway reduced (from Q lanes) to two lanes. Traffic building up");
	r.insert(566, "carriageway reduced (from Q lanes) to three lanes. Stationary traffic");
	r.insert(567, "carriageway reduced (from Q lanes) to three lanes. Danger of stationary traffic");
	r.insert(568, "carriageway reduced (from Q lanes) to three lanes. Queuing traffic");
	r.insert(569, "carriageway reduced (from Q lanes) to three lanes. Danger of queuing traffic");
	r.insert(570, "carriageway reduced (from Q lanes) to three lanes. Slow traffic");
	r.insert(571, "carriageway reduced (from Q lanes) to three lanes. Slow traffic expected");
	r.insert(572, "carriageway reduced (from Q lanes) to three lanes. Heavy traffic");
	r.insert(573, "carriageway reduced (from Q lanes) to three lanes. Heavy traffic expected");
	r.insert(574, "carriageway reduced (from Q lanes) to three lanes. Traffic flowing freely");
	r.insert(575, "carriageway reduced (from Q lanes) to three lanes. Traffic building up");
	r.insert(576, "contraflow. Stationary traffic");
	r.insert(577, "contraflow. Stationary traffic for 1 km");
	r.insert(578, "contraflow. Stationary traffic for 2 km");
	r.insert(579, "contraflow. Stationary traffic for 4 km");
	r.insert(580, "contraflow. Stationary traffic for 6 km");
	r.insert(581, "contraflow. Stationary traffic for 10 km");
	r.insert(582, "contraflow. Danger of stationary traffic");
	r.insert(583, "contraflow. Queuing traffic ");
	r.insert(584, "contraflow. Queuing traffic for 1 km");
	r.insert(585, "contraflow. Queuing traffic for 2 km");
	r.insert(586, "contraflow. Queuing traffic for 4 km");
	r.insert(587, "contraflow. Queuing traffic for 6 km");
	r.insert(588, "contraflow. Queuing traffic for 10 km");
	r.insert(589, "contraflow. Danger of queuing traffic");
	r.insert(590, "contraflow. Slow traffic ");
	r.insert(591, "contraflow. Slow traffic for 1 km");
	r.insert(592, "contraflow. Slow traffic for 2 km");
	r.insert(593, "contraflow. Slow traffic for 4 km");
	r.insert(594, "contraflow. Slow traffic for 6 km");
	r.insert(595, "contraflow. Slow traffic for 10 km");
	r.insert(596, "contraflow. Slow traffic expected ");
	r.insert(597, "contraflow. Heavy traffic ");
	r.insert(598, "contraflow. Heavy traffic expected ");
	r.insert(599, "contraflow. Traffic flowing freely");
	r.insert(600, "contraflow. Traffic building up");
	r.insert(601, "contraflow. Carriageway reduced (from Q lanes) to one lane");
	r.insert(602, "contraflow. Carriageway reduced (from Q lanes) to two lanes ");
	r.insert(603, "contraflow. Carriageway reduced (from Q lanes) to three lanes");
	r.insert(604, "narrow lanes. Stationary traffic");
	r.insert(605, "narrow lanes. Danger of stationary traffic ");
	r.insert(606, "narrow lanes. Queuing traffic");
	r.insert(607, "narrow lanes. Danger of queuing traffic");
	r.insert(608, "narrow lanes. Slow traffic");
	r.insert(609, "narrow lanes. Slow traffic expected");
	r.insert(610, "narrow lanes. Heavy traffic");
	r.insert(611, "narrow lanes. Heavy traffic expected");
	r.insert(612, "narrow lanes. Traffic flowing freely");
	r.insert(613, "narrow lanes. Traffic building up");
	r.insert(614, "contraflow with narrow lanes. Stationary traffic");
	r.insert(615, "contraflow with narrow lanes. Stationary traffic. Danger of stationary traffic");
	r.insert(616, "contraflow with narrow lanes. Queuing traffic");
	r.insert(617, "contraflow with narrow lanes. Danger of queuing traffic");
	r.insert(618, "contraflow with narrow lanes. Slow traffic");
	r.insert(619, "contraflow with narrow lanes. Slow traffic expected");
	r.insert(620, "contraflow with narrow lanes. Heavy traffic");
	r.insert(621, "contraflow with narrow lanes. Heavy traffic expected");
	r.insert(622, "contraflow with narrow lanes. Traffic flowing freely");
	r.insert(623, "contraflow with narrow lanes. Traffic building up");
	r.insert(624, "lane closures removed");
	r.insert(625, "message cancelled");
	r.insert(626, "blocked ahead. Slow traffic for 3 km");
	r.insert(627, "no motor vehicles without catalytic converters");
	r.insert(628, "no motor vehicles with even-numbered registration plates");
	r.insert(629, "no motor vehicles with odd-numbered registration plates");
	r.insert(630, "open");
	r.insert(631, "road cleared");
	r.insert(632, "entry reopened");
	r.insert(633, "exit reopened");
	r.insert(634, "all carriageways reopened");
	r.insert(635, "motor vehicle restrictions lifted");
	r.insert(636, "traffic restrictions lifted  {reopened for all traffic}");
	r.insert(637, "emergency lane closed");
	r.insert(638, "turning lane closed");
	r.insert(639, "crawler lane closed");
	r.insert(640, "slow vehicle lane closed");
	r.insert(641, "one lane closed");
	r.insert(642, "emergency lane blocked");
	r.insert(643, "turning lane blocked");
	r.insert(644, "crawler lane blocked");
	r.insert(645, "slow vehicle lane blocked");
	r.insert(646, "one lane blocked");
	r.insert(647, "(Q person) carpool lane in operation");
	r.insert(648, "(Q person) carpool lane closed");
	r.insert(649, "(Q person) carpool lane blocked");
	r.insert(650, "carpool restrictions changed (to Q persons per vehicle)");
	r.insert(651, "(Q) lanes closed. Stationary traffic for 3 km");
	r.insert(652, "(Q) lanes closed. Queuing traffic for 3 km");
	r.insert(653, "(Q) lanes closed. Slow traffic for 3 km");
	r.insert(654, "contraflow. Stationary traffic for 3 km");
	r.insert(655, "contraflow. Queuing traffic for 3 km");
	r.insert(656, "contraflow. Slow traffic for 3 km");
	r.insert(657, "lane blockages cleared");
	r.insert(658, "contraflow removed");
	r.insert(659, "(Q person) carpool restrictions lifted");
	r.insert(660, "lane restrictions lifted");
	r.insert(661, "use of hard shoulder allowed");
	r.insert(662, "normal lane regulations restored");
	r.insert(663, "all carriageways cleared");
	r.insert(664, "carriageway closed");
	r.insert(665, "both directions closed");
	r.insert(666, "intermittent short term closures");
	r.insert(671, "bus lane available for carpools (with at least Q occupants)");
	r.insert(672, "message cancelled");
	r.insert(673, "message cancelled");
	r.insert(675, "(Q) salting vehicles");
	r.insert(676, "bus lane blocked");
	r.insert(678, "heavy vehicle lane closed");
	r.insert(679, "heavy vehicle lane blocked");
	r.insert(680, "reopened for through traffic");
	r.insert(681, "(Q) snowploughs");
	r.insert(701, "(Q sets of) roadworks");
	r.insert(702, "(Q sets of) major roadworks ");
	r.insert(703, "(Q sets of) maintenance work ");
	r.insert(704, "(Q sections of) resurfacing work ");
	r.insert(705, "(Q sets of) central reservation work ");
	r.insert(706, "(Q sets of) road marking work ");
	r.insert(707, "bridge maintenance work (at Q bridges)");
	r.insert(708, "(Q sets of) temporary traffic lights");
	r.insert(709, "(Q sections of) blasting work ");
	r.insert(710, "(Q sets of) roadworks. Stationary traffic");
	r.insert(711, "(Q sets of) roadworks. Stationary traffic for 1 km");
	r.insert(712, "(Q sets of) roadworks. Stationary traffic for 2 km");
	r.insert(713, "(Q sets of) roadworks. Stationary traffic for 4 km");
	r.insert(714, "(Q sets of) roadworks. Stationary traffic for 6 km");
	r.insert(715, "(Q sets of) roadworks. Stationary traffic for 10 km");
	r.insert(716, "(Q sets of) roadworks. Danger of stationary traffic");
	r.insert(717, "(Q sets of) roadworks. Queuing traffic");
	r.insert(718, "(Q sets of) roadworks. Queuing traffic for 1 km");
	r.insert(719, "(Q sets of) roadworks. Queuing traffic for 2 km");
	r.insert(720, "(Q sets of) roadworks. Queuing traffic for 4 km");
	r.insert(721, "(Q sets of) roadworks. Queuing traffic for 6 km");
	r.insert(722, "(Q sets of) roadworks. Queuing traffic for 10 km");
	r.insert(723, "(Q sets of) roadworks. Danger of queuing traffic");
	r.insert(724, "(Q sets of) roadworks. Slow traffic ");
	r.insert(725, "(Q sets of) roadworks. Slow traffic for 1 km");
	r.insert(726, "(Q sets of) roadworks. Slow traffic for 2 km");
	r.insert(727, "(Q sets of) roadworks. Slow traffic for 4 km");
	r.insert(728, "(Q sets of) roadworks. Slow traffic for 6 km");
	r.insert(729, "(Q sets of) roadworks. Slow traffic for 10 km");
	r.insert(730, "(Q sets of) roadworks. Slow traffic expected");
	r.insert(731, "(Q sets of) roadworks. Heavy traffic ");
	r.insert(732, "(Q sets of) roadworks. Heavy traffic expected");
	r.insert(733, "(Q sets of) roadworks. Traffic flowing freely");
	r.insert(734, "(Q sets of) roadworks. Traffic building up");
	r.insert(735, "closed due to (Q sets of) roadworks");
	r.insert(736, "(Q sets of) roadworks. Right lane closed");
	r.insert(737, "(Q sets of) roadworks. Centre lane closed");
	r.insert(738, "(Q sets of) roadworks. Left lane closed");
	r.insert(739, "(Q sets of) roadworks. Hard shoulder closed");
	r.insert(740, "(Q sets of) roadworks. Two lanes closed");
	r.insert(741, "(Q sets of) roadworks. Three lanes closed");
	r.insert(742, "(Q sets of) roadworks. Single alternate line traffic");
	r.insert(743, "roadworks. Carriageway reduced (from Q lanes) to one lane");
	r.insert(744, "roadworks. Carriageway reduced (from Q lanes) to two lanes");
	r.insert(745, "roadworks. Carriageway reduced (from Q lanes) to three lanes");
	r.insert(746, "(Q sets of) roadworks. Contraflow");
	r.insert(747, "roadworks. Delays (Q)");
	r.insert(748, "roadworks. Delays (Q) expected");
	r.insert(749, "roadworks. Long delays (Q)");
	r.insert(750, "(Q sections of) resurfacing work. Stationary traffic");
	r.insert(751, "(Q sections of) resurfacing work. Stationary traffic for 1 km");
	r.insert(752, "(Q sections of) resurfacing work. Stationary traffic for 2 km");
	r.insert(753, "(Q sections of) resurfacing work. Stationary traffic for 4 km");
	r.insert(754, "(Q sections of) resurfacing work. Stationary traffic for 6 km");
	r.insert(755, "(Q sections of) resurfacing work. Stationary traffic for 10 km");
	r.insert(756, "(Q sections of) resurfacing work. Danger of stationary traffic");
	r.insert(757, "(Q sections of) resurfacing work. Queuing traffic");
	r.insert(758, "(Q sections of) resurfacing work. Queuing traffic for 1 km");
	r.insert(759, "(Q sections of) resurfacing work. Queuing traffic for 2 km");
	r.insert(760, "(Q sections of) resurfacing work. Queuing traffic for 4 km");
	r.insert(761, "(Q sections of) resurfacing work. Queuing traffic for 6 km");
	r.insert(762, "(Q sections of) resurfacing work. Queuing traffic for 10 km");
	r.insert(763, "(Q sections of) resurfacing work. Danger of queuing traffic");
	r.insert(764, "(Q sections of) resurfacing work. Slow traffic");
	r.insert(765, "(Q sections of) resurfacing work. Slow traffic for 1 km");
	r.insert(766, "(Q sections of) resurfacing work. Slow traffic for 2 km");
	r.insert(767, "(Q sections of) resurfacing work. Slow traffic for 4 km");
	r.insert(768, "(Q sections of) resurfacing work. Slow traffic for 6 km");
	r.insert(769, "(Q sections of) resurfacing work. Slow traffic for 10 km");
	r.insert(770, "(Q sections of) resurfacing work. Slow traffic expected");
	r.insert(771, "(Q sections of) resurfacing work. Heavy traffic");
	r.insert(772, "(Q sections of) resurfacing work. Heavy traffic expected");
	r.insert(773, "(Q sections of) resurfacing work. Traffic flowing freely");
	r.insert(774, "(Q sections of) resurfacing work. Traffic building up");
	r.insert(775, "(Q sections of) resurfacing work. Single alternate line traffic");
	r.insert(776, "resurfacing work. Carriageway reduced (from Q lanes) to one lane");
	r.insert(777, "resurfacing work. Carriageway reduced (from Q lanes) to two lanes");
	r.insert(778, "resurfacing work. Carriageway reduced (from Q lanes) to three lanes");
	r.insert(779, "(Q sections of) resurfacing work. Contraflow");
	r.insert(780, "resurfacing work. Delays (Q)");
	r.insert(781, "resurfacing work. Delays (Q) expected");
	r.insert(782, "resurfacing work. Long delays (Q)");
	r.insert(783, "(Q sets of) road marking work. Stationary traffic");
	r.insert(784, "(Q sets of) road marking work. Danger of stationary traffic");
	r.insert(785, "(Q sets of) road marking work. Queuing traffic");
	r.insert(786, "(Q sets of) road marking work. Danger of queuing traffic");
	r.insert(787, "(Q sets of) road marking work. Slow traffic");
	r.insert(788, "(Q sets of) road marking work. Slow traffic expected");
	r.insert(789, "(Q sets of) road marking work. Heavy traffic");
	r.insert(790, "(Q sets of) road marking work. Heavy traffic expected");
	r.insert(791, "(Q sets of) road marking work. Traffic flowing freely");
	r.insert(792, "(Q sets of) road marking work. Traffic building up");
	r.insert(793, "(Q sets of) road marking work. Right lane closed");
	r.insert(794, "(Q sets of) road marking work. Centre lane closed ");
	r.insert(795, "(Q sets of) road marking work. Left lane closed");
	r.insert(796, "(Q sets of) road marking work. Hard shoulder closed");
	r.insert(797, "(Q sets of) road marking work. Two lanes closed");
	r.insert(798, "(Q sets of) road marking work. Three lanes closed");
	r.insert(799, "closed for bridge demolition work (at Q bridges)");
	r.insert(800, "roadworks cleared");
	r.insert(801, "message cancelled");
	r.insert(802, "(Q sets of) long-term roadworks");
	r.insert(803, "(Q sets of) construction work");
	r.insert(804, "(Q sets of) slow moving maintenance vehicles ");
	r.insert(805, "bridge demolition work (at Q bridges)");
	r.insert(806, "(Q sets of) water main work");
	r.insert(807, "(Q sets of) gas main work ");
	r.insert(808, "(Q sets of) work on buried cables");
	r.insert(809, "(Q sets of) work on buried services");
	r.insert(810, "new roadworks layout");
	r.insert(811, "new road layout");
	r.insert(812, "(Q sets of) roadworks. Stationary traffic for 3 km");
	r.insert(813, "(Q sets of) roadworks. Queuing traffic for 3 km");
	r.insert(814, "(Q sets of) roadworks. Slow traffic for 3 km");
	r.insert(815, "(Q sets of) roadworks during the day time");
	r.insert(816, "(Q sets of) roadworks during off-peak periods");
	r.insert(817, "(Q sets of) roadworks during the night ");
	r.insert(818, "(Q sections of) resurfacing work. Stationary traffic for 3 km");
	r.insert(819, "(Q sections of) resurfacing work. Queuing traffic for 3 km");
	r.insert(820, "(Q sections of) resurfacing work. Slow traffic for 3 km");
	r.insert(821, "(Q sets of) resurfacing work during the day time");
	r.insert(822, "(Q sets of) resurfacing work during off-peak periods");
	r.insert(823, "(Q sets of) resurfacing work during the night ");
	r.insert(824, "(Q sets of) road marking work. Danger");
	r.insert(825, "(Q sets of) slow moving maintenance vehicles. Stationary traffic");
	r.insert(826, "(Q sets of) slow moving maintenance vehicles. Danger of stationary traffic ");
	r.insert(827, "(Q sets of) slow moving maintenance vehicles. Queuing traffic");
	r.insert(828, "(Q sets of) slow moving maintenance vehicles. Danger of queuing traffic ");
	r.insert(829, "(Q sets of) slow moving maintenance vehicles. Slow traffic");
	r.insert(830, "(Q sets of) slow moving maintenance vehicles. Slow traffic expected");
	r.insert(831, "(Q sets of) slow moving maintenance vehicles. Heavy traffic");
	r.insert(832, "(Q sets of) slow moving maintenance vehicles. Heavy traffic expected");
	r.insert(833, "(Q sets of) slow moving maintenance vehicles. Traffic flowing freely");
	r.insert(834, "(Q sets of) slow moving maintenance vehicles. Traffic building up");
	r.insert(835, "(Q sets of) slow moving maintenance vehicles. Right lane closed");
	r.insert(836, "(Q sets of) slow moving maintenance vehicles. Centre lane closed ");
	r.insert(837, "(Q sets of) slow moving maintenance vehicles. Left lane closed");
	r.insert(838, "(Q sets of) slow moving maintenance vehicles. Two lanes closed");
	r.insert(839, "(Q sets of) slow moving maintenance vehicles. Three lanes closed");
	r.insert(840, "water main work. Delays (Q)");
	r.insert(841, "water main work. Delays (Q) expected");
	r.insert(842, "water main work. Long delays (Q)");
	r.insert(843, "gas main work. Delays (Q)");
	r.insert(844, "gas main work. Delays (Q) expected");
	r.insert(845, "gas main work. Long delays (Q)");
	r.insert(846, "work on buried cables. Delays (Q)");
	r.insert(847, "work on buried cables. Delays (Q) expected");
	r.insert(848, "work on buried cables. Long delays (Q)");
	r.insert(849, "work on buried services. Delays (Q)");
	r.insert(850, "work on buried services. Delays (Q) expected");
	r.insert(851, "work on buried services. Long delays (Q)");
	r.insert(852, "construction traffic merging");
	r.insert(853, "roadwork clearance in progress");
	r.insert(854, "maintenance work cleared");
	r.insert(855, "road layout unchanged");
	r.insert(856, "construction traffic merging. Danger");
	r.insert(857, "(Q) unprotected accident area(s)");
	r.insert(858, "danger of(Q) unprotected accident area(s)");
	r.insert(859, "(Q) unlit vehicle(s) on the road");
	r.insert(860, "danger of (Q) unlit vehicle(s) on the road");
	r.insert(861, "snow and ice debris");
	r.insert(862, "danger of snow and ice debris");
	r.insert(897, "people throwing objects onto the road. Danger");
	r.insert(898, "obstruction warning withdrawn");
	r.insert(899, "clearance work in progress, road free again");
	r.insert(900, "flooding expected");
	r.insert(901, "(Q) obstruction(s) on roadway {something that does block the road or part of it}");
	r.insert(902, "(Q) obstructions on the road. Danger");
	r.insert(903, "spillage on the road");
	r.insert(904, "storm damage");
	r.insert(905, "(Q) fallen trees");
	r.insert(906, "(Q) fallen trees. Danger ");
	r.insert(907, "flooding");
	r.insert(908, "flooding. Danger");
	r.insert(909, "flash floods");
	r.insert(910, "danger of flash floods ");
	r.insert(911, "avalanches");
	r.insert(912, "avalanche risk ");
	r.insert(913, "rockfalls");
	r.insert(914, "landslips");
	r.insert(915, "earthquake damage ");
	r.insert(916, "road surface in poor condition ");
	r.insert(917, "subsidence");
	r.insert(918, "(Q) collapsed sewer(s)");
	r.insert(919, "burst water main");
	r.insert(920, "gas leak");
	r.insert(921, "serious fire");
	r.insert(922, "animals on roadway");
	r.insert(923, "animals on the road. Danger");
	r.insert(924, "clearance work");
	r.insert(925, "blocked by storm damage");
	r.insert(926, "blocked by (Q) fallen trees");
	r.insert(927, "(Q) fallen tree(s). Passable with care");
	r.insert(928, "flooding. Stationary traffic");
	r.insert(929, "flooding. Danger of stationary traffic");
	r.insert(930, "flooding. Queuing traffic");
	r.insert(931, "flooding. Danger of queuing traffic");
	r.insert(932, "flooding. Slow traffic");
	r.insert(933, "flooding. Slow traffic expected");
	r.insert(934, "flooding. Heavy traffic ");
	r.insert(935, "flooding. Heavy traffic expected");
	r.insert(936, "flooding. Traffic flowing freely");
	r.insert(937, "flooding. Traffic building up");
	r.insert(938, "closed due to flooding");
	r.insert(939, "flooding. Delays (Q)");
	r.insert(940, "flooding. Delays (Q) expected");
	r.insert(941, "flooding. Long delays (Q)");
	r.insert(942, "flooding. Passable with care");
	r.insert(943, "closed due to avalanches");
	r.insert(944, "avalanches. Passable with care (above Q hundred metres)");
	r.insert(945, "closed due to rockfalls");
	r.insert(946, "rockfalls. Passable with care");
	r.insert(947, "road closed due to landslips");
	r.insert(948, "landslips. Passable with care");
	r.insert(949, "closed due to subsidence");
	r.insert(950, "subsidence. Single alternate line traffic");
	r.insert(951, "subsidence. Carriageway reduced (from Q lanes) to one lane");
	r.insert(952, "subsidence. Carriageway reduced (from Q lanes) to two lanes");
	r.insert(953, "subsidence. Carriageway reduced (from Q lanes) to three lanes");
	r.insert(954, "subsidence. Contraflow in operation");
	r.insert(955, "subsidence. Passable with care");
	r.insert(956, "closed due to sewer collapse");
	r.insert(957, "road closed due to burst water main");
	r.insert(958, "burst water main. Delays (Q)");
	r.insert(959, "burst water main. Delays (Q) expected");
	r.insert(960, "burst water main. Long delays (Q)");
	r.insert(961, "closed due to gas leak");
	r.insert(962, "gas leak. Delays (Q)");
	r.insert(963, "gas leak. Delays (Q) expected");
	r.insert(964, "gas leak. Long delays (Q)");
	r.insert(965, "closed due to serious fire");
	r.insert(966, "serious fire. Delays (Q)");
	r.insert(967, "serious fire. Delays (Q) expected");
	r.insert(968, "serious fire. Long delays (Q)");
	r.insert(969, "closed for clearance work ");
	r.insert(970, "road free again");
	r.insert(971, "message cancelled");
	r.insert(972, "storm damage expected");
	r.insert(973, "fallen power cables");
	r.insert(974, "sewer overflow");
	r.insert(975, "ice build-up");
	r.insert(976, "mud slide");
	r.insert(977, "grass fire");
	r.insert(978, "air crash");
	r.insert(979, "rail crash");
	r.insert(980, "blocked by (Q) obstruction(s) on the road");
	r.insert(981, "(Q) obstructions on the road. Passable with care");
	r.insert(982, "blocked due to spillage on roadway");
	r.insert(983, "spillage on the road. Passable with care");
	r.insert(984, "spillage on the road. Danger");
	r.insert(985, "storm damage. Passable with care");
	r.insert(986, "storm damage. Danger");
	r.insert(987, "blocked by fallen power cables");
	r.insert(988, "fallen power cables. Passable with care");
	r.insert(989, "fallen power cables. Danger");
	r.insert(990, "sewer overflow. Danger");
	r.insert(991, "flash floods. Danger");
	r.insert(992, "avalanches. Danger");
	r.insert(993, "closed due to avalanche risk");
	r.insert(994, "avalanche risk. Danger ");
	r.insert(995, "closed due to ice build-up");
	r.insert(996, "ice build-up. Passable with care (above Q hundred metres)");
	r.insert(997, "ice build-up. Single alternate traffic");
	r.insert(998, "rockfalls. Danger");
	r.insert(999, "landslips. Danger");
	r.insert(1000, "earthquake damage. Danger ");
	r.insert(1001, "hazardous driving conditions (above Q hundred metres)");
	r.insert(1002, "danger of aquaplaning ");
	r.insert(1003, "slippery road (above Q hundred metres)");
	r.insert(1004, "mud on road");
	r.insert(1005, "leaves on road");
	r.insert(1006, "ice (above Q hundred metres)");
	r.insert(1007, "danger of ice (above Q hundred metres)");
	r.insert(1008, "black ice (above Q hundred metres)");
	r.insert(1009, "freezing rain (above Q hundred metres)");
	r.insert(1010, "wet and icy roads (above Q hundred metres) ");
	r.insert(1011, "slush (above Q hundred metres)");
	r.insert(1012, "snow on the road (above Q hundred metres)");
	r.insert(1013, "packed snow (above Q hundred metres)");
	r.insert(1014, "fresh snow (above Q hundred metres)");
	r.insert(1015, "deep snow (above Q hundred metres)");
	r.insert(1016, "snow drifts (above Q hundred metres)");
	r.insert(1017, "slippery due to spillage on roadway");
	r.insert(1018, "slippery road (above Q hundred metres) due to snow");
	r.insert(1019, "slippery road (above Q hundred metres) due to frost");
	r.insert(1020, "road blocked by snow (above Q hundred metres)");
	r.insert(1021, "snow on the road. Carriageway reduced (from Q lanes) to one lane");
	r.insert(1022, "snow on the road. Carriageway reduced (from Q lanes) to two lanes");
	r.insert(1023, "snow on the road. Carriageway reduced (from Q lanes) to three lanes");
	r.insert(1024, "conditions of road surface improved");
	r.insert(1025, "message cancelled");
	r.insert(1026, "subsidence. Danger");
	r.insert(1027, "sewer collapse. Delays (Q)");
	r.insert(1028, "sewer collapse. Delays (Q) expected");
	r.insert(1029, "sewer collapse. Long delays (Q)");
	r.insert(1030, "sewer collapse. Danger ");
	r.insert(1031, "burst water main. Danger");
	r.insert(1032, "gas leak. Danger");
	r.insert(1033, "serious fire. Danger");
	r.insert(1034, "clearance work. Danger");
	r.insert(1035, "impassable (above Q hundred metres)");
	r.insert(1036, "almost impassable (above Q hundred metres)");
	r.insert(1037, "extremely hazardous driving conditions (above Q hundred metres)");
	r.insert(1038, "difficult driving conditions (above Q hundred metres)");
	r.insert(1039, "passable with care (up to Q hundred metres)");
	r.insert(1040, "passable (up to Q hundred metres)");
	r.insert(1041, "surface water hazard");
	r.insert(1042, "loose sand on road");
	r.insert(1043, "loose chippings");
	r.insert(1044, "oil on road");
	r.insert(1045, "petrol on road");
	r.insert(1047, "icy patches (above Q hundred metres)");
	r.insert(1048, "danger of icy patches (above Q hundred metres)");
	r.insert(1050, "danger of black ice (above Q hundred metres)");
	r.insert(1054, "slippery due to loose sand on roadway");
	r.insert(1055, "mud on road. Danger");
	r.insert(1056, "loose chippings. Danger");
	r.insert(1057, "oil on road. Danger");
	r.insert(1058, "petrol on road. Danger");
	r.insert(1059, "road surface in poor condition. Danger");
	r.insert(1060, "icy patches (above Q hundred metres) on bridges");
	r.insert(1061, "danger of icy patches (above Q hundred metres) on bridges");
	r.insert(1062, "icy patches (above Q hundred metres) on bridges, in shaded areas and on slip roads");
	r.insert(1063, "impassable for heavy vehicles (over Q)");
	r.insert(1064, "impassable (above Q hundred metres) for vehicles with trailers");
	r.insert(1065, "driving conditions improved");
	r.insert(1066, "rescue and recovery work in progress. Danger");
	r.insert(1067, "large animals on roadway");
	r.insert(1068, "herds of animals on roadway");
	r.insert(1069, "skid hazard reduced");
	r.insert(1070, "snow cleared");
	r.insert(1073, "extremely hazardous driving conditions expected (above Q  hundred meters)");
	r.insert(1074, "freezing rain expected (above Q hundred metres)");
	r.insert(1075, "danger of road being blocked by snow (above Q hundred metres)");
	r.insert(1079, "temperature falling rapidly (to Q)");
	r.insert(1080, "extreme heat (up to Q)");
	r.insert(1081, "extreme cold (of Q)");
	r.insert(1082, "less extreme temperatures");
	r.insert(1083, "current temperature (Q)");
	r.insert(1084, "house fire");
	r.insert(1085, "forest fire");
	r.insert(1086, "vehicle stuck under bridge");
	r.insert(1090, "volcano eruption warning");
	r.insert(1101, "heavy snowfall (Q) ");
	r.insert(1102, "heavy snowfall (Q). Visibility reduced to <30 m");
	r.insert(1103, "heavy snowfall (Q). Visibility reduced to <50 m");
	r.insert(1104, "snowfall (Q) ");
	r.insert(1105, "snowfall (Q). Visibility reduced to <100 m");
	r.insert(1106, "hail (visibility reduced to Q)");
	r.insert(1107, "sleet (visibility reduced to Q)");
	r.insert(1108, "thunderstorms (visibility reduced to Q)");
	r.insert(1109, "heavy rain (Q)");
	r.insert(1110, "heavy rain (Q). Visibility reduced to <30 m");
	r.insert(1111, "heavy rain (Q). Visibility reduced to <50 m");
	r.insert(1112, "rain (Q)");
	r.insert(1113, "rain (Q). Visibility reduced to <100 m");
	r.insert(1114, "showers (visibility reduced to Q)");
	r.insert(1115, "heavy frost");
	r.insert(1116, "frost");
	r.insert(1126, "weather situation improved");
	r.insert(1127, "message cancelled");
	r.insert(1128, "winter storm (visibility reduced to Q)");
	r.insert(1130, "blizzard (visibility reduced to Q)");
	r.insert(1132, "damaging hail (visibility reduced to Q)");
	r.insert(1134, "heavy snowfall. Visibility reduced (to Q)");
	r.insert(1135, "snowfall. Visibility reduced (to Q)");
	r.insert(1136, "heavy rain. Visibility reduced (to Q)");
	r.insert(1137, "rain. Visibility reduced (to Q)");
	r.insert(1165, "rain changing to snow");
	r.insert(1166, "snow changing to rain");
	r.insert(1170, "heavy snowfall (Q) expected");
	r.insert(1171, "heavy rain (Q) expected");
	r.insert(1172, "weather expected to improve");
	r.insert(1173, "blizzard (with visibility reduced to Q) expected ");
	r.insert(1174, "damaging hail (with visibility reduced to Q) expected");
	r.insert(1175, "reduced visibility (to Q) expected");
	r.insert(1176, "freezing fog expected (with visibility reduced to Q). Danger of slippery roads");
	r.insert(1177, "dense fog (with visibility reduced to Q) expected");
	r.insert(1178, "patchy fog (with visibility reduced to Q) expected");
	r.insert(1179, "visibility expected to improve");
	r.insert(1180, "adverse weather warning withdrawn");
	r.insert(1190, "severe smog");
	r.insert(1191, "severe exhaust pollution");
	r.insert(1201, "tornadoes ");
	r.insert(1202, "hurricane force winds (Q)");
	r.insert(1203, "gales (Q)");
	r.insert(1204, "storm force winds (Q)");
	r.insert(1205, "strong winds (Q)");
	r.insert(1209, "gusty winds (Q)");
	r.insert(1210, "crosswinds (Q)");
	r.insert(1211, "strong winds (Q) affecting high-sided vehicles");
	r.insert(1212, "closed for high-sided vehicles due to strong winds (Q)");
	r.insert(1213, "strong winds easing");
	r.insert(1214, "message cancelled");
	r.insert(1215, "restrictions for high-sided vehicles lifted");
	r.insert(1217, "tornado warning ended");
	r.insert(1301, "dense fog (visibility reduced to Q)");
	r.insert(1302, "dense fog. Visibility reduced to <30 m");
	r.insert(1303, "dense fog. Visibility reduced to <50 m");
	r.insert(1304, "fog (visibility reduced to Q)");
	r.insert(1305, "fog. Visibility reduced to <100 m");
	r.insert(1307, "patchy fog (visibility reduced to Q)");
	r.insert(1308, "freezing fog (visibility reduced to Q)");
	r.insert(1309, "smoke hazard (visibility reduced to Q)");
	r.insert(1310, "blowing dust (visibility reduced to Q)");
	r.insert(1312, "snowfall and fog (visibility reduced to Q)");
	r.insert(1313, "visibility improved");
	r.insert(1314, "message cancelled");
	r.insert(1318, "visibility reduced (to Q)");
	r.insert(1319, "visibility reduced to <30 m");
	r.insert(1320, "visibility reduced to <50 m");
	r.insert(1321, "visibility reduced to <100 m");
	r.insert(1322, "white out (visibility reduced to Q)");
	r.insert(1323, "blowing snow (visibility reduced to Q)");
	r.insert(1324, "spray hazard (visibility reduced to Q)");
	r.insert(1325, "low sun glare");
	r.insert(1326, "sandstorms (visibility reduced to Q)");
	r.insert(1332, "smog alert");
	r.insert(1337, "freezing fog (visibility reduced to Q). Slippery roads");
	r.insert(1338, "no motor vehicles due to smog alert");
	r.insert(1340, "swarms of insects (visibility reduced to Q)");
	r.insert(1345, "fog clearing");
	r.insert(1346, "fog forecast withdrawn");
	r.insert(1449, "emergency training in progress");
	r.insert(1450, "international sports meeting");
	r.insert(1451, "match");
	r.insert(1452, "tournament");
	r.insert(1453, "athletics meeting");
	r.insert(1454, "ball game");
	r.insert(1455, "boxing tournament");
	r.insert(1456, "bull fight");
	r.insert(1457, "cricket match");
	r.insert(1458, "cycle race");
	r.insert(1459, "football match");
	r.insert(1460, "golf tournament");
	r.insert(1461, "marathon");
	r.insert(1462, "race meeting");
	r.insert(1463, "rugby match");
	r.insert(1464, "show jumping");
	r.insert(1465, "tennis tournament");
	r.insert(1466, "water sports meeting");
	r.insert(1467, "winter sports meeting");
	r.insert(1468, "funfair");
	r.insert(1469, "trade fair");
	r.insert(1470, "procession");
	r.insert(1471, "sightseers obstructing access");
	r.insert(1472, "people on roadway");
	r.insert(1473, "children on roadway");
	r.insert(1474, "cyclists on roadway");
	r.insert(1475, "strike");
	r.insert(1476, "security incident");
	r.insert(1477, "police checkpoint");
	r.insert(1478, "terrorist incident");
	r.insert(1479, "gunfire on roadway, danger");
	r.insert(1480, "civil emergency");
	r.insert(1481, "air raid, danger");
	r.insert(1482, "people on roadway. Danger");
	r.insert(1483, "children on roadway. Danger");
	r.insert(1484, "cyclists on roadway. Danger");
	r.insert(1485, "closed due to security incident");
	r.insert(1486, "security incident. Delays (Q)");
	r.insert(1487, "security incident. Delays (Q) expected");
	r.insert(1488, "security incident. Long delays (Q)");
	r.insert(1489, "police checkpoint. Delays (Q)");
	r.insert(1490, "police checkpoint. Delays (Q) expected");
	r.insert(1491, "police checkpoint. Long delays (Q)");
	r.insert(1492, "security alert withdrawn");
	r.insert(1493, "sports traffic cleared");
	r.insert(1494, "evacuation");
	r.insert(1495, "evacuation. Heavy traffic ");
	r.insert(1496, "traffic disruption cleared");
	r.insert(1497, "military training in progress");
	r.insert(1498, "police activity ongoing");
	r.insert(1499, "medical emergency ongoing");
	r.insert(1500, "child abduction in progress");
	r.insert(1501, "major event");
	r.insert(1502, "sports event meeting");
	r.insert(1503, "show ");
	r.insert(1504, "festival");
	r.insert(1505, "exhibition");
	r.insert(1506, "fair");
	r.insert(1507, "market");
	r.insert(1508, "ceremonial event");
	r.insert(1509, "state occasion");
	r.insert(1510, "parade");
	r.insert(1511, "crowd");
	r.insert(1512, "march");
	r.insert(1513, "demonstration");
	r.insert(1514, "public disturbance");
	r.insert(1515, "security alert");
	r.insert(1516, "bomb alert");
	r.insert(1517, "major event. Stationary traffic ");
	r.insert(1518, "major event. Danger of stationary traffic");
	r.insert(1519, "major event. Queuing traffic ");
	r.insert(1520, "major event. Danger of queuing traffic");
	r.insert(1521, "major event. Slow traffic ");
	r.insert(1522, "major event. Slow traffic expected ");
	r.insert(1523, "major event. Heavy traffic ");
	r.insert(1524, "major event. Heavy traffic expected ");
	r.insert(1525, "major event. Traffic flowing freely");
	r.insert(1526, "major event. Traffic building up ");
	r.insert(1527, "closed due to major event");
	r.insert(1528, "major event. Delays (Q)");
	r.insert(1529, "major event. Delays (Q) expected");
	r.insert(1530, "major event. Long delays (Q)");
	r.insert(1531, "sports meeting. Stationary traffic");
	r.insert(1532, "sports meeting. Danger of stationary traffic");
	r.insert(1533, "sports meeting. Queuing traffic");
	r.insert(1534, "sports meeting. Danger of queuing traffic");
	r.insert(1535, "sports meeting. Slow traffic");
	r.insert(1536, "sports meeting. Slow traffic expected");
	r.insert(1537, "sports meeting. Heavy traffic ");
	r.insert(1538, "sports meeting. Heavy traffic expected");
	r.insert(1539, "sports meeting. Traffic flowing freely");
	r.insert(1540, "sports meeting. Traffic building up");
	r.insert(1541, "closed due to sports meeting");
	r.insert(1542, "sports meeting. Delays (Q)");
	r.insert(1543, "sports meeting. Delays (Q) expected");
	r.insert(1544, "sports meeting. Long delays (Q)");
	r.insert(1545, "fair. Stationary traffic");
	r.insert(1546, "fair. Danger of stationary traffic");
	r.insert(1547, "fair. Queuing traffic");
	r.insert(1548, "fair. Danger of queuing traffic");
	r.insert(1549, "fair. Slow traffic");
	r.insert(1550, "fair. Slow traffic expected");
	r.insert(1551, "fair. Heavy traffic ");
	r.insert(1552, "fair. Heavy traffic expected");
	r.insert(1553, "fair. Traffic flowing freely");
	r.insert(1554, "fair. Traffic building up");
	r.insert(1555, "closed due to fair");
	r.insert(1556, "fair. Delays (Q)");
	r.insert(1557, "fair. Delays (Q) expected");
	r.insert(1558, "fair. Long delays (Q)");
	r.insert(1559, "closed due to parade");
	r.insert(1560, "parade. Delays (Q)");
	r.insert(1561, "parade. Delays (Q) expected");
	r.insert(1562, "parade. Long delays (Q)");
	r.insert(1563, "closed due to strike");
	r.insert(1564, "strike. Delays (Q)");
	r.insert(1565, "strike. Delays (Q) expected");
	r.insert(1566, "strike. Long delays (Q)");
	r.insert(1567, "closed due to demonstration");
	r.insert(1568, "demonstration. Delays (Q)");
	r.insert(1569, "demonstration. Delays (Q) expected");
	r.insert(1570, "demonstration. Long delays (Q)");
	r.insert(1571, "security alert. Stationary traffic");
	r.insert(1572, "security alert. Danger of stationary traffic");
	r.insert(1573, "security alert. Queuing traffic");
	r.insert(1574, "security alert. Danger of queuing traffic");
	r.insert(1575, "security alert. Slow traffic ");
	r.insert(1576, "security alert. Slow traffic expected");
	r.insert(1577, "security alert. Heavy traffic ");
	r.insert(1578, "security alert. Heavy traffic expected");
	r.insert(1579, "security alert. Traffic building up");
	r.insert(1580, "closed due to security alert");
	r.insert(1581, "security alert. Delays (Q)");
	r.insert(1582, "security alert. Delays (Q) expected");
	r.insert(1583, "security alert. Long delays (Q)");
	r.insert(1584, "traffic has returned to normal");
	r.insert(1585, "message cancelled");
	r.insert(1586, "security alert. Traffic flowing freely");
	r.insert(1587, "air raid warning cancelled");
	r.insert(1588, "civil emergency cancelled");
	r.insert(1589, "message cancelled");
	r.insert(1590, "several major events");
	r.insert(1591, "information about major event no longer valid");
	r.insert(1592, "automobile race");
	r.insert(1593, "baseball game");
	r.insert(1594, "basketball game");
	r.insert(1595, "boat race");
	r.insert(1596, "concert");
	r.insert(1597, "hockey game");
	r.insert(1601, "delays (Q)");
	r.insert(1602, "delays up to 15 minutes");
	r.insert(1603, "delays up to 30 minutes");
	r.insert(1604, "delays up to one hour");
	r.insert(1605, "delays up to two hours");
	r.insert(1606, "delays of several hours");
	r.insert(1607, "delays (Q) expected");
	r.insert(1608, "long delays (Q)");
	r.insert(1609, "delays (Q) for heavy vehicles");
	r.insert(1610, "delays up to 15 minutes for heavy lorr(y/ies)");
	r.insert(1611, "delays up to 30 minutes for heavy lorr(y/ies) ");
	r.insert(1612, "delays up to one hour for heavy lorr(y/ies) ");
	r.insert(1613, "delays up to two hours for heavy lorr(y/ies) ");
	r.insert(1614, "delays of several hours for heavy lorr(y/ies) ");
	r.insert(1615, "service suspended (until Q)");
	r.insert(1616, "(Q) service withdrawn");
	r.insert(1617, "(Q) service(s) fully booked");
	r.insert(1618, "(Q) service(s) fully booked for heavy vehicles");
	r.insert(1619, "normal services resumed");
	r.insert(1620, "message cancelled");
	r.insert(1621, "delays up to 5 minutes");
	r.insert(1622, "delays up to 10 minutes");
	r.insert(1623, "delays up to 20 minutes");
	r.insert(1624, "delays up to 25 minutes");
	r.insert(1625, "delays up to 40 minutes");
	r.insert(1626, "delays up to 50 minutes");
	r.insert(1627, "delays up to 90 minutes");
	r.insert(1628, "delays up to three hours");
	r.insert(1629, "delays up to four hours");
	r.insert(1630, "delays up to five hours");
	r.insert(1631, "very long delays (Q)");
	r.insert(1632, "delays of uncertain duration");
	r.insert(1633, "delayed until further notice");
	r.insert(1634, "cancellations");
	r.insert(1635, "park and ride service not operating (until Q)");
	r.insert(1636, "special public transport services operating (until Q)");
	r.insert(1637, "normal services not operating (until Q)");
	r.insert(1638, "rail services not operating (until Q)");
	r.insert(1639, "bus services not operating (until Q)");
	r.insert(1640, "shuttle service operating (until Q)");
	r.insert(1641, "free shuttle service operating (until Q)");
	r.insert(1642, "delays (Q) for heavy lorr(y/ies) ");
	r.insert(1643, "delays (Q) for buses");
	r.insert(1644, "(Q) service(s) fully booked for heavy lorr(y/ies)");
	r.insert(1645, "(Q) service(s) fully booked for buses");
	r.insert(1646, "next departure (Q) for heavy lorr(y/ies)");
	r.insert(1647, "next departure (Q) for buses");
	r.insert(1648, "delays cleared");
	r.insert(1649, "rapid transit service not operating (until Q)");
	r.insert(1650, "delays (Q) possible");
	r.insert(1651, "underground service not operating (until Q)");
	r.insert(1652, "cancellations expected");
	r.insert(1653, "long delays expected");
	r.insert(1654, "very long delays expected");
	r.insert(1655, "all services fully booked (until Q)");
	r.insert(1656, "next arrival (Q)");
	r.insert(1657, "rail services irregular. Delays (Q)");
	r.insert(1658, "bus services irregular. Delays (Q)");
	r.insert(1659, "underground services irregular");
	r.insert(1660, "normal public transport services resumed");
	r.insert(1661, "ferry service not operating (until Q)");
	r.insert(1662, "park and ride trip time (Q)");
	r.insert(1663, "delay expected to be cleared");
	r.insert(1664, "demonstration by vehicles");
	r.insert(1695, "current trip time (Q)");
	r.insert(1696, "expected trip time (Q)");
	r.insert(1700, "(Q) slow moving maintenance vehicle(s)");
	r.insert(1701, "(Q) vehicle(s) on wrong carriageway");
	r.insert(1702, "dangerous vehicle warning cleared");
	r.insert(1703, "message cancelled");
	r.insert(1704, "(Q) reckless driver(s)");
	r.insert(1705, "(Q) prohibited vehicle(s) on the roadway");
	r.insert(1706, "(Q) emergency vehicles");
	r.insert(1707, "(Q) high-speed emergency vehicles");
	r.insert(1708, "high-speed chase (involving Q vehicles)");
	r.insert(1709, "spillage occurring from moving vehicle");
	r.insert(1710, "objects falling from moving vehicle");
	r.insert(1711, "emergency vehicle warning cleared");
	r.insert(1712, "road cleared");
	r.insert(1720, "rail services irregular");
	r.insert(1721, "public transport services not operating");
	r.insert(1731, "(Q) abnormal load(s), danger");
	r.insert(1732, "(Q) wide load(s), danger");
	r.insert(1733, "(Q) long load(s), danger");
	r.insert(1734, "(Q) slow vehicle(s), danger");
	r.insert(1735, "(Q) track-laying vehicle(s), danger");
	r.insert(1736, "(Q) vehicle(s) carrying hazardous materials. Danger");
	r.insert(1737, "(Q) convoy(s), danger");
	r.insert(1738, "(Q) military convoy(s), danger");
	r.insert(1739, "(Q) overheight load(s), danger");
	r.insert(1740, "abnormal load causing slow traffic. Delays (Q)");
	r.insert(1741, "convoy causing slow traffic. Delays (Q)");
	r.insert(1751, "(Q) abnormal load(s)");
	r.insert(1752, "(Q) wide load(s)");
	r.insert(1753, "(Q) long load(s)");
	r.insert(1754, "(Q) slow vehicle(s)");
	r.insert(1755, "(Q) convoy(s)");
	r.insert(1756, "abnormal load. Delays (Q)");
	r.insert(1757, "abnormal load. Delays (Q) expected");
	r.insert(1758, "abnormal load. Long delays (Q)");
	r.insert(1759, "convoy causing delays (Q)");
	r.insert(1760, "convoy. Delays (Q) expected");
	r.insert(1761, "convoy causing long delays (Q)");
	r.insert(1762, "exceptional load warning cleared");
	r.insert(1763, "message cancelled");
	r.insert(1764, "(Q) track-laying vehicle(s)");
	r.insert(1765, "(Q) vehicle(s) carrying hazardous materials");
	r.insert(1766, "(Q) military convoy(s)");
	r.insert(1767, "(Q) abnormal load(s). No overtaking ");
	r.insert(1768, "Vehicles carrying hazardous materials have to stop at next safe place!");
	r.insert(1769, "hazardous load warning cleared");
	r.insert(1770, "convoy cleared");
	r.insert(1771, "warning cleared");
	r.insert(1801, "lane control signs not working");
	r.insert(1802, "emergency telephones not working ");
	r.insert(1803, "emergency telephone number not working");
	r.insert(1804, "(Q sets of) traffic lights not working");
	r.insert(1805, "(Q sets of) traffic lights working incorrectly");
	r.insert(1806, "level crossing failure");
	r.insert(1807, "(Q sets of) traffic lights not working. Stationary traffic");
	r.insert(1808, "(Q sets of) traffic lights not working. Danger of stationary traffic");
	r.insert(1809, "(Q sets of) traffic lights not working. Queuing traffic");
	r.insert(1810, "(Q sets of) traffic lights not working. Danger of queuing traffic");
	r.insert(1811, "(Q sets of) traffic lights not working. Slow traffic");
	r.insert(1812, "(Q sets of) traffic lights not working. Slow traffic expected");
	r.insert(1813, "(Q sets of) traffic lights not working. Heavy traffic");
	r.insert(1814, "(Q sets of) traffic lights not working. Heavy traffic expected");
	r.insert(1815, "(Q sets of) traffic lights not working. Traffic flowing freely");
	r.insert(1816, "(Q sets of) traffic lights not working. Traffic building up");
	r.insert(1817, "traffic lights not working. Delays (Q)");
	r.insert(1818, "traffic lights not working. Delays (Q) expected");
	r.insert(1819, "traffic lights not working. Long delays (Q)");
	r.insert(1820, "level crossing failure. Stationary traffic");
	r.insert(1821, "level crossing failure. Danger of stationary traffic");
	r.insert(1822, "level crossing failure. Queuing traffic");
	r.insert(1823, "level crossing failure. Danger of queuing traffic");
	r.insert(1824, "level crossing failure. Slow traffic");
	r.insert(1825, "level crossing failure. Slow traffic expected");
	r.insert(1826, "level crossing failure. Heavy traffic");
	r.insert(1827, "level crossing failure. Heavy traffic expected");
	r.insert(1828, "level crossing failure. Traffic flowing freely");
	r.insert(1829, "level crossing failure. Traffic building up");
	r.insert(1830, "level crossing failure. Delays (Q)");
	r.insert(1831, "level crossing failure. Delays (Q) expected");
	r.insert(1832, "level crossing failure. Long delays (Q)");
	r.insert(1833, "electronic signs repaired");
	r.insert(1834, "emergency call facilities restored");
	r.insert(1835, "traffic signals repaired");
	r.insert(1836, "level crossing now working normally");
	r.insert(1837, "message cancelled");
	r.insert(1838, "lane control signs working incorrectly");
	r.insert(1839, "lane control signs operating");
	r.insert(1840, "variable message signs not working");
	r.insert(1841, "variable message signs working incorrectly");
	r.insert(1842, "variable message signs operating");
	r.insert(1843, "(Q sets of) ramp control signals not working");
	r.insert(1844, "(Q sets of) ramp control signals working incorrectly");
	r.insert(1845, "(Q sets of) temporary traffic lights not working");
	r.insert(1846, "(Q sets of) temporary traffic lights working incorrectly");
	r.insert(1847, "traffic signal control computer not working");
	r.insert(1848, "traffic signal timings changed");
	r.insert(1849, "tunnel ventilation not working");
	r.insert(1850, "lane control signs not working. Danger ");
	r.insert(1851, "temporary width limit (Q)");
	r.insert(1852, "temporary width limit lifted");
	r.insert(1854, "traffic regulations have been changed");
	r.insert(1855, "less than 50 parking spaces available");
	r.insert(1856, "no parking information available (until Q)");
	r.insert(1857, "message cancelled");
	r.insert(1858, "Snowplough. Delays (Q)");
	r.insert(1861, "temporary height limit (Q)");
	r.insert(1862, "temporary height limit lifted");
	r.insert(1863, "(Q) automatic payment lanes not working");
	r.insert(1864, "lane control signs working incorrectly. Danger");
	r.insert(1865, "emergency telephones out of order. Extra police patrols in operation");
	r.insert(1866, "emergency telephones out of order. In emergency, wait for police patrol");
	r.insert(1867, "(Q sets of) traffic lights not working. Danger");
	r.insert(1868, "traffic lights working incorrectly. Delays (Q)");
	r.insert(1869, "traffic lights working incorrectly. Delays (Q) expected");
	r.insert(1870, "traffic lights working incorrectly. Long delays (Q)");
	r.insert(1871, "temporary axle load limit (Q)");
	r.insert(1872, "temporary gross weight limit (Q)");
	r.insert(1873, "temporary gross weight limit lifted");
	r.insert(1874, "temporary axle weight limit lifted");
	r.insert(1875, "(Q sets of) traffic lights working incorrectly. Danger");
	r.insert(1876, "temporary traffic lights not working. Delays (Q)");
	r.insert(1877, "temporary traffic lights not working. Delays (Q) expected");
	r.insert(1878, "temporary traffic lights not working. Long delays (Q)");
	r.insert(1879, "(Q sets of) temporary traffic lights not working. Danger");
	r.insert(1880, "traffic signal control computer not working. Delays (Q)");
	r.insert(1881, "temporary length limit (Q)");
	r.insert(1882, "temporary length limit lifted");
	r.insert(1883, "message cancelled");
	r.insert(1884, "traffic signal control computer not working. Delays (Q) expected");
	r.insert(1885, "traffic signal control computer not working. Long delays (Q)");
	r.insert(1886, "normal parking restrictions lifted");
	r.insert(1887, "special parking restrictions in force");
	r.insert(1888, "10% full");
	r.insert(1889, "20% full");
	r.insert(1890, "30% full");
	r.insert(1891, "40% full");
	r.insert(1892, "50% full");
	r.insert(1893, "60% full");
	r.insert(1894, "70% full");
	r.insert(1895, "80% full");
	r.insert(1896, "90% full");
	r.insert(1897, "less than 10 parking spaces available");
	r.insert(1898, "less than 20 parking spaces available");
	r.insert(1899, "less than 30 parking spaces available");
	r.insert(1900, "less than 40 parking spaces available");
	r.insert(1901, "next departure (Q)");
	r.insert(1902, "next departure (Q) for heavy vehicles");
	r.insert(1903, "car park (Q) full");
	r.insert(1904, "all car parks (Q) full");
	r.insert(1905, "less than (Q) car parking spaces available");
	r.insert(1906, "park and ride service operating (until Q)");
	r.insert(1907, "(null event) {no event description, but location etc. given in message}");
	r.insert(1908, "switch your car radio (to Q)");
	r.insert(1909, "alarm call: important new information on this frequency follows now in normal programme");
	r.insert(1910, "alarm set: new information will be broadcast between these times in normal programme");
	r.insert(1911, "message cancelled");
	r.insert(1913, "switch your car radio (to Q)");
	r.insert(1914, "no information available (until Q)");
	r.insert(1915, "this message is for test purposes only (number Q), please ignore");
	r.insert(1916, "no information available (until Q) due to technical problems");
	r.insert(1917, "automatic toll system not working, pay manually");
	r.insert(1918, "full");
	r.insert(1920, "only a few parking spaces available");
	r.insert(1921, "(Q) parking spaces available");
	r.insert(1922, "expect car park to be full");
	r.insert(1923, "expect no parking spaces available");
	r.insert(1924, "multi story car parks full");
	r.insert(1925, "no problems to report with park and ride services");
	r.insert(1926, "no parking spaces available");
	r.insert(1927, "no parking (until Q)");
	r.insert(1928, "special parking restrictions lifted");
	r.insert(1929, "urgent information will be given (at Q) on normal programme broadcasts");
	r.insert(1930, "this TMC-service is not active (until Q)");
	r.insert(1931, "detailed information will be given (at Q) on normal programme broadcasts");
	r.insert(1932, "detailed information is provided by another TMC service");
	r.insert(1934, "no park and ride information available (until Q)");
	r.insert(1938, "park and ride information service resumed");
	r.insert(1939, "travel information telephone service available");
	r.insert(1940, "additional regional information is provided by another TMC service ");
	r.insert(1941, "additional local information is provided by another TMC service");
	r.insert(1942, "additional public transport information is provided by another TMC service");
	r.insert(1943, "national traffic information is provided by another TMC service");
	r.insert(1944, "this service provides major road information");
	r.insert(1945, "this service provides regional travel information");
	r.insert(1946, "this service provides local travel information");
	r.insert(1947, "no detailed regional information provided by this service");
	r.insert(1948, "no detailed local information provided by this service");
	r.insert(1949, "no cross-border information provided by this service");
	r.insert(1950, "information restricted to this area");
	r.insert(1951, "no new traffic information available (until Q)");
	r.insert(1952, "no public transport information available");
	r.insert(1953, "this TMC-service is being suspended (at Q)");
	r.insert(1954, "active TMC-service will resume (at Q)");
	r.insert(1955, "reference to audio programmes no longer valid");
	r.insert(1956, "reference to other TMC services no longer valid");
	r.insert(1957, "previous announcement about this or other TMC services no longer valid");
	r.insert(1961, "allow emergency vehicles to pass in the carpool lane");
	r.insert(1962, "carpool lane available for all vehicles");
	r.insert(1963, "police directing traffic via the carpool lane");
	r.insert(1964, "rail information service not available");
	r.insert(1965, "rail information service resumed");
	r.insert(1966, "rapid transit information service not available");
	r.insert(1967, "rapid transit information service resumed");
	r.insert(1971, "police directing traffic");
	r.insert(1972, "buslane available for all vehicles");
	r.insert(1973, "police directing traffic via the buslane");
	r.insert(1974, "allow emergency vehicles to pass");
	r.insert(1975, "overtaking prohibited for heavy vehicles (over Q)");
	r.insert(1976, "overtaking prohibited");
	r.insert(1977, "allow emergency vehicles to pass in the heavy vehicle lane");
	r.insert(1978, "heavy vehicle lane available for all vehicles");
	r.insert(1979, "police directing traffic via the heavy vehicle lane");
	r.insert(1980, "overtaking prohibited for heavy lorries (over Q)");
	r.insert(1981, "drivers of heavy lorries (over Q) are recommended to stop at next safe place");
	r.insert(1982, "buslane closed");
	r.insert(1983, "power failure");
	r.insert(1985, "overtaking restriction lifted");
	r.insert(1986, "Low Emission Zone restriction in force");
	r.insert(1990, "car park closed (until Q)");
	r.insert(1991, "danger of waiting vehicles on roadway");
	r.insert(1993, "number of parking spaces decreasing");
	r.insert(1994, "number of parking spaces constant");
	r.insert(1995, "number of parking spaces increasing");
	r.insert(1998, "dangerous situation on exit slip road");
	r.insert(1999, "dangerous situation on entry slip road");
	r.insert(2000, "closed due to smog alert (until Q)");
	r.insert(2006, "closed for vehicles with less than three occupants  {not valid for lorries}");
	r.insert(2007, "closed for vehicles with only one occupant {not valid for lorries}");
	r.insert(2013, "service area busy");
	r.insert(2021, "service not operating, substitute service available");
	r.insert(2022, "public transport strike");
	r.insert(2028, "message cancelled");
	r.insert(2029, "message cancelled");
	r.insert(2030, "message cancelled");
	r.insert(2033, "message cancelled");
	r.insert(2034, "message cancelled");
	r.insert(2035, "message cancelled");
	r.insert(2038, "message cancelled");
	r.insert(2039, "message cancelled");
	r.insert(2040, "message cancelled");
	r.insert(2041, "nothing to report");
	r.insert(2042, "ice build-up on cable structure");
	r.insert(2043, "road salted");
	r.insert(2044, "danger of snow patches");
	r.insert(2045, "snow patches");
	r.insert(2046, "Convoy service required due to bad weather");
	r.insert(2047, "(null message)  {completely silent message, see protocol, sect. 3.5.4}");
	return r;
}
